### ISSUE TITLE
AES GUI: include both modes (ECB and CBC)

### ISSUE THREAD

**Issue by ColinConduff** [user404d/CS6001-AES#2]
I think we'll need to include the CBC mode as well.  The aes_io functions are already set up for it.  I think it would just require adding a checkbox to the gui, as well as passing in different arguments to the encrypt_file and decrypt_file functions.  Check out the test_cbc_on_file function in the aes_test.py file for an example.

**Comment by spayne92** [comment]
Ok, I think I can get that done. Do you guys want to meet to work on this
weeks homework/project?

**Comment by user404d** [comment]
I have gotten a good head start on this. There are still some things that need to be done before this issue is closed. [current progress](https://github.com/user404d/CS6001-AES/commit/2b39062e536d6202ce658bb4fe17c27bf39e2a9b).
